"""Sample project data for demonstration."""

from datetime import date, timedelta


def create_sample_project() -> dict:
    """Create a sample project with tasks, dependencies, and resources."""
    today = date.today()
    monday = today - timedelta(days=today.weekday())  # Start of this week

    tasks = [
        # Phase 1: Planning
        {
            "id": 1, "name": "Webサイトリニューアルプロジェクト", "duration": 60,
            "start_date": monday, "end_date": monday + timedelta(days=84),
            "progress": 35, "wbs_level": 0, "wbs": "1",
            "is_summary": True, "is_milestone": False, "is_critical": False,
            "parent_id": None, "sort_order": 0, "cost": 5000000,
            "notes": "", "predecessors": "", "resource_names": "",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 2, "name": "企画・要件定義フェーズ", "duration": 15,
            "start_date": monday, "end_date": monday + timedelta(days=20),
            "progress": 80, "wbs_level": 1, "wbs": "1.1",
            "is_summary": True, "is_milestone": False, "is_critical": True,
            "parent_id": 1, "sort_order": 1, "cost": 800000,
            "notes": "", "predecessors": "", "resource_names": "",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 3, "name": "現状分析・要件ヒアリング", "duration": 5,
            "start_date": monday, "end_date": monday + timedelta(days=6),
            "progress": 100, "wbs_level": 2, "wbs": "1.1.1",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 2, "sort_order": 2, "cost": 200000,
            "notes": "クライアントとの打ち合わせ完了", "predecessors": "",
            "resource_names": "田中",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 4, "name": "要件定義書作成", "duration": 5,
            "start_date": monday + timedelta(days=7), "end_date": monday + timedelta(days=13),
            "progress": 100, "wbs_level": 2, "wbs": "1.1.2",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 2, "sort_order": 3, "cost": 300000,
            "notes": "", "predecessors": "3FS", "resource_names": "田中, 佐藤",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 5, "name": "要件定義完了", "duration": 0,
            "start_date": monday + timedelta(days=14), "end_date": monday + timedelta(days=14),
            "progress": 50, "wbs_level": 2, "wbs": "1.1.3",
            "is_summary": False, "is_milestone": True, "is_critical": True,
            "parent_id": 2, "sort_order": 4, "cost": 0,
            "notes": "", "predecessors": "4FS", "resource_names": "",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        # Phase 2: Design
        {
            "id": 6, "name": "デザインフェーズ", "duration": 15,
            "start_date": monday + timedelta(days=14), "end_date": monday + timedelta(days=34),
            "progress": 40, "wbs_level": 1, "wbs": "1.2",
            "is_summary": True, "is_milestone": False, "is_critical": True,
            "parent_id": 1, "sort_order": 5, "cost": 1200000,
            "notes": "", "predecessors": "", "resource_names": "",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 7, "name": "ワイヤーフレーム作成", "duration": 5,
            "start_date": monday + timedelta(days=14), "end_date": monday + timedelta(days=20),
            "progress": 80, "wbs_level": 2, "wbs": "1.2.1",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 6, "sort_order": 6, "cost": 400000,
            "notes": "", "predecessors": "5FS", "resource_names": "鈴木",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 8, "name": "UIデザイン", "duration": 7,
            "start_date": monday + timedelta(days=21), "end_date": monday + timedelta(days=30),
            "progress": 20, "wbs_level": 2, "wbs": "1.2.2",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 6, "sort_order": 7, "cost": 500000,
            "notes": "", "predecessors": "7FS", "resource_names": "鈴木",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 9, "name": "デザインレビュー・承認", "duration": 3,
            "start_date": monday + timedelta(days=31), "end_date": monday + timedelta(days=34),
            "progress": 0, "wbs_level": 2, "wbs": "1.2.3",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 6, "sort_order": 8, "cost": 100000,
            "notes": "", "predecessors": "8FS", "resource_names": "田中, 鈴木",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        # Phase 3: Development
        {
            "id": 10, "name": "開発フェーズ", "duration": 25,
            "start_date": monday + timedelta(days=35), "end_date": monday + timedelta(days=69),
            "progress": 10, "wbs_level": 1, "wbs": "1.3",
            "is_summary": True, "is_milestone": False, "is_critical": False,
            "parent_id": 1, "sort_order": 9, "cost": 2000000,
            "notes": "", "predecessors": "", "resource_names": "",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 11, "name": "フロントエンド開発", "duration": 15,
            "start_date": monday + timedelta(days=35), "end_date": monday + timedelta(days=55),
            "progress": 15, "wbs_level": 2, "wbs": "1.3.1",
            "is_summary": False, "is_milestone": False, "is_critical": False,
            "parent_id": 10, "sort_order": 10, "cost": 800000,
            "notes": "", "predecessors": "9FS", "resource_names": "佐藤",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 12, "name": "バックエンド開発", "duration": 20,
            "start_date": monday + timedelta(days=35), "end_date": monday + timedelta(days=62),
            "progress": 10, "wbs_level": 2, "wbs": "1.3.2",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 10, "sort_order": 11, "cost": 1000000,
            "notes": "", "predecessors": "9FS", "resource_names": "高橋",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 13, "name": "結合テスト", "duration": 5,
            "start_date": monday + timedelta(days=63), "end_date": monday + timedelta(days=69),
            "progress": 0, "wbs_level": 2, "wbs": "1.3.3",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 10, "sort_order": 12, "cost": 200000,
            "notes": "", "predecessors": "11FS, 12FS", "resource_names": "佐藤, 高橋",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        # Phase 4: Testing & Launch
        {
            "id": 14, "name": "テスト・リリースフェーズ", "duration": 15,
            "start_date": monday + timedelta(days=70), "end_date": monday + timedelta(days=84),
            "progress": 0, "wbs_level": 1, "wbs": "1.4",
            "is_summary": True, "is_milestone": False, "is_critical": True,
            "parent_id": 1, "sort_order": 13, "cost": 1000000,
            "notes": "", "predecessors": "", "resource_names": "",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 15, "name": "ユーザー受入テスト", "duration": 5,
            "start_date": monday + timedelta(days=70), "end_date": monday + timedelta(days=76),
            "progress": 0, "wbs_level": 2, "wbs": "1.4.1",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 14, "sort_order": 14, "cost": 300000,
            "notes": "", "predecessors": "13FS", "resource_names": "田中",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 16, "name": "バグ修正・最適化", "duration": 5,
            "start_date": monday + timedelta(days=77), "end_date": monday + timedelta(days=83),
            "progress": 0, "wbs_level": 2, "wbs": "1.4.2",
            "is_summary": False, "is_milestone": False, "is_critical": True,
            "parent_id": 14, "sort_order": 15, "cost": 500000,
            "notes": "", "predecessors": "15FS", "resource_names": "佐藤, 高橋",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
        {
            "id": 17, "name": "本番リリース 🚀", "duration": 0,
            "start_date": monday + timedelta(days=84), "end_date": monday + timedelta(days=84),
            "progress": 0, "wbs_level": 2, "wbs": "1.4.3",
            "is_summary": False, "is_milestone": True, "is_critical": True,
            "parent_id": 14, "sort_order": 16, "cost": 0,
            "notes": "最終リリース日", "predecessors": "16FS", "resource_names": "",
            "constraint_type": None, "constraint_date": None,
            "manual_scheduling": False, "baseline_start": None,
            "baseline_end": None, "baseline_duration": None,
            "actual_start": None, "actual_end": None,
        },
    ]

    dependencies = [
        {"id": 1, "predecessor_id": 3, "successor_id": 4, "dep_type": "FS", "lag": 0},
        {"id": 2, "predecessor_id": 4, "successor_id": 5, "dep_type": "FS", "lag": 0},
        {"id": 3, "predecessor_id": 5, "successor_id": 7, "dep_type": "FS", "lag": 0},
        {"id": 4, "predecessor_id": 7, "successor_id": 8, "dep_type": "FS", "lag": 0},
        {"id": 5, "predecessor_id": 8, "successor_id": 9, "dep_type": "FS", "lag": 0},
        {"id": 6, "predecessor_id": 9, "successor_id": 11, "dep_type": "FS", "lag": 0},
        {"id": 7, "predecessor_id": 9, "successor_id": 12, "dep_type": "FS", "lag": 0},
        {"id": 8, "predecessor_id": 11, "successor_id": 13, "dep_type": "FS", "lag": 0},
        {"id": 9, "predecessor_id": 12, "successor_id": 13, "dep_type": "FS", "lag": 0},
        {"id": 10, "predecessor_id": 13, "successor_id": 15, "dep_type": "FS", "lag": 0},
        {"id": 11, "predecessor_id": 15, "successor_id": 16, "dep_type": "FS", "lag": 0},
        {"id": 12, "predecessor_id": 16, "successor_id": 17, "dep_type": "FS", "lag": 0},
    ]

    resources = [
        {"id": 1, "name": "田中 太郎", "resource_type": "work", "max_units": 100,
         "standard_rate": 5000, "overtime_rate": 7500, "email": "tanaka@example.com"},
        {"id": 2, "name": "佐藤 花子", "resource_type": "work", "max_units": 100,
         "standard_rate": 4500, "overtime_rate": 6750, "email": "sato@example.com"},
        {"id": 3, "name": "鈴木 一郎", "resource_type": "work", "max_units": 100,
         "standard_rate": 5500, "overtime_rate": 8250, "email": "suzuki@example.com"},
        {"id": 4, "name": "高橋 誠", "resource_type": "work", "max_units": 100,
         "standard_rate": 6000, "overtime_rate": 9000, "email": "takahashi@example.com"},
        {"id": 5, "name": "開発サーバー", "resource_type": "material", "max_units": 100,
         "standard_rate": 50000, "overtime_rate": 0, "email": ""},
    ]

    return {
        "project": {
            "name": "Webサイトリニューアルプロジェクト",
            "start_date": monday,
        },
        "tasks": tasks,
        "dependencies": dependencies,
        "resources": resources,
    }
